---
- name: Enable Permissive Script Security
  lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: '^(.+\=\_)'
    line: '\1 -Dpermissive-script-security.enabled=no_security"'
    backrefs: true
  notify:
    - Restart Jenkins
  when:
    - ansible_os_family == "RedHat"
