---
- name: JCasC configs
  block:
    - name: Create JCasC directory
      file:
        path: '{{ jenkins2_home_directory }}/{{ jenkins2_jcasc_directory }}'
        state: directory
        owner: '{{ jenkins2_user }}'
        group: '{{ jenkins2_user }}'
        mode: 0770

    - name: Create JCasC configuration
      template:
        src: jcasc/jenkins.yml.j2
        owner: '{{ jenkins2_user }}'
        group: '{{ jenkins2_user }}'
        dest: '{{ jenkins2_home_directory }}/{{ jenkins2_jcasc_directory }}/jenkins.yml'
        mode: 0440
      register: jcasc_result
  become: true

- name: Apply JCasC configuration
  jenkins_script:
    url: '{{ jenkins2_config_proto }}://{{ jenkins2_host_address }}:{{ jenkins2_config_http_port }}'
    script: '{{ lookup("template", "jenkins_configure_plugins/configure-jcasc.groovy.j2") }}'
    user: '{{ jenkins2_cli_username }}'
    password: '{{ jenkins2_cli_password }}'
    timeout: '240'
    validate_certs: false
  register: casc_configure_result
  failed_when:
    - (casc_configure_result.output | regex_replace('\\s*Result:\\s*(.*)\\n*$', '\\1') | from_json).failed
  changed_when:
    - (casc_configure_result.output | regex_replace('\\s*Result:\\s*(.*)\\n*$', '\\1') | from_json).changed
