FROM {{ item.image }}
MAINTAINER "Viktor Utkin Viktor_Utkin@epam.com"
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
RUN yum makecache fast && yum update -y && yum -y install initscripts systemd-sysv redhat-lsb-core sudo bash iproute \
yum-plugin-ovl && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all && touch /etc/sysconfig/network;
VOLUME [ "/sys/fs/cgroup" ]
ENTRYPOINT ["/usr/sbin/init"]
