---
- name: Force gathering facts
  hosts: all
  gather_facts: True
  roles: []

- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
    - role: ansible-role-jenkins
      jenkins2_pipeline_libraries_enabled: True
      jenkins2_pipeline_libraries_url: "https://example.com/example.git"
      jenkins2_bitbucket_project_enabled: True
      jenkins2_sonarqube_enabled: True
