---
- name: Export certificate and private key into a bundle
  command: >-
    openssl pkcs12 -export
    -in '{{ local_cert_file_path }}/{{ jenkins2_local_cert_file_name }}'
    -inkey '{{ local_pkey_file_path }}/{{ jenkins2_local_pkey_file_name }}'
    -name '{{ ansible_hostname }}'
    -passout pass:{{ jenkins2_ssl_key_store_password }}
    -out '{{ ansible_hostname }}.p12'
    -name 'default'
  args:
    chdir: '{{ jenkins2_ssl_key_store_path }}/'
    creates: '{{ ansible_hostname }}.p12'
  become_flags: '-i'
  become_method: sudo

- name: Import the PKCS12 file into a new java keystore
  java_cert:
    pkcs12_path: '{{ jenkins2_ssl_key_store_path }}/{{ ansible_hostname }}.p12'
    pkcs12_password: '{{ jenkins2_ssl_key_store_password }}'
    pkcs12_alias: default
    keystore_path: '{{ jenkins2_ssl_key_store }}'
    keystore_pass: '{{ jenkins2_ssl_key_store_password }}'
    keystore_create: True
    state: present
  become_flags: '-i'
  become_method: sudo
