---
- name: Force gathering facts
  hosts: all
  gather_facts: True
  roles: []

- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
    - role: ansible-role-jenkins
      jenkins2_pipeline_libraries_enabled: True
      jenkins2_pipeline_libraries_url: "https://example.com/example.git"
      jenkins2_bitbucket_project_enabled: True
      jenkins2_sonarqube_enabled: True
      jenkins2_custom_files_enabled: True
      jenkins2_gitlab_enabled: True
      jenkins2_seed_job_enable: True
      gitlab_external_url: "https://localhost"
      gitlab_project_group: "test"
      gitlab_project_name: "test"
      ci_test_jenkins_slave_label: "ci_slaves"
      feature_verification_jenkins_slave_label: "fv_slaves"
